/**
 * Zips made by Info-ZIP (`zip -X -r`, and `-fz` for forced zip64) of a
 * tasks/ folder: a.json (deflated), b.json and Café.json (stored). Shared by
 * the zip and Dropbox client tests.
 */
export const PLAIN_ZIP = "UEsDBAoAAAAAAJJ9Q10AAAAAAAAAAAAAAAAGAAAAdGFza3MvUEsDBBQAAAAIAJJ9Q13pwFPhGAAAACQBAAAMAAAAdGFza3MvYS5qc29uq1YqySzJSVWyUipKLUhNLFEYpdAopVoAUEsDBAoAAAAAAJJ9Q13qP6sUCgAAAAoAAAAQAAAAdGFza3MvQ2Fmw6kuanNvbnsidCI6IsOpIn1QSwMECgAAAAAAkn1DXfnvvnEBAAAAAQAAAAwAAAB0YXNrcy9iLmpzb25iUEsBAh4DCgAAAAAAkn1DXQAAAAAAAAAAAAAAAAYAAAAAAAAAAAAQAO1BAAAAAHRhc2tzL1BLAQIeAxQAAAAIAJJ9Q13pwFPhGAAAACQBAAAMAAAAAAAAAAEAAACkgSQAAAB0YXNrcy9hLmpzb25QSwECHgMKAAAAAACSfUNd6j+rFAoAAAAKAAAAEAAAAAAAAAABAAAApIFmAAAAdGFza3MvQ2Fmw6kuanNvblBLAQIeAwoAAAAAAJJ9Q135775xAQAAAAEAAAAMAAAAAAAAAAEAAACkgZ4AAAB0YXNrcy9iLmpzb25QSwUGAAAAAAQABADmAAAAyQAAAAAA";
export const ZIP64_ZIP = "UEsDBC0AAAAAAJJ9Q10AAAAA//////////8GABQAdGFza3MvAQAQAAAAAAAAAAAAAAAAAAAAAABQSwMELQAAAAgAkn1DXenAU+H//////////wwAFAB0YXNrcy9hLmpzb24BABAAJAEAAAAAAAAYAAAAAAAAAKtWKsksyUlVslIqSi1ITSxRGKXQKKVaAFBLAwQtAAAAAACSfUNd6j+rFP//////////EAAUAHRhc2tzL0NhZsOpLmpzb24BABAACgAAAAAAAAAKAAAAAAAAAHsidCI6IsOpIn1QSwMELQAAAAAAkn1DXfnvvnH//////////wwAFAB0YXNrcy9iLmpzb24BABAAAQAAAAAAAAABAAAAAAAAAGJQSwECHgMKAAAAAACSfUNdAAAAAAAAAAD/////BgAMAAAAAAAAABAA7UEAAAAAdGFza3MvAQAIAAAAAAAAAAAAUEsBAh4DLQAAAAgAkn1DXenAU+EYAAAA/////wwADAAAAAAAAQAAAKSBOAAAAHRhc2tzL2EuanNvbgEACAAkAQAAAAAAAFBLAQIeAy0AAAAAAJJ9Q13qP6sUCgAAAP////8QAAwAAAAAAAEAAACkgY4AAAB0YXNrcy9DYWbDqS5qc29uAQAIAAoAAAAAAAAAUEsBAh4DLQAAAAAAkn1DXfnvvnEBAAAA/////wwADAAAAAAAAQAAAKSB2gAAAHRhc2tzL2IuanNvbgEACAABAAAAAAAAAFBLBgYsAAAAAAAAAB4DLQAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAWAQAAAAAAABkBAAAAAAAAUEsGBwAAAAAvAgAAAAAAAAEAAABQSwUGAAAAAAQABAAWAQAA/////wAA";
export const A_JSON = `{"title":"${"repeat ".repeat(40)}"}`;

export const fromBase64 = (s: string): Uint8Array => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));
